# Generated by Django 4.0.5 on 2022-06-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Y_date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='X_text',
            new_name='text',
        ),
    ]
